CREATE DATABASE FE

USE FE

CREATE TABLE R
(
	ID int IDENTITY PRIMARY KEY,
	A int,
	B int 
)

CREATE TABLE S
(
	ID int IDENTITY PRIMARY KEY,
	C int,
	D int 
)

CREATE TABLE T
(
	ID int IDENTITY PRIMARY KEY,
	E int,
	F int 
)
DROP TABLE R
DROP TABLE S
DROP TABLE T
INSERT INTO R VALUES(0, 1)
INSERT INTO R VALUES(1, 0)
INSERT INTO R VALUES(1, 1)

INSERT INTO S VALUES(0, 1)
INSERT INTO S VALUES(1, 0)
INSERT INTO S VALUES(1, 1)

INSERT INTO T VALUES(0, 1)
INSERT INTO T VALUES(1, 0)
INSERT INTO T VALUES(1, 1)

SELECT A, F, SUM(C), SUM(D)
FROM R, S, T
WHERE B = C AND D = E
GROUP BY A, F
HAVING COUNT(*) > 1
-----------------------
CREATE TABLE R
(
	ID int IDENTITY PRIMARY KEY,
	x int,
	y int 
)

INSERT INTO R VALUES(1, 2)
INSERT INTO R VALUES(1, 2)
INSERT INTO R VALUES(2, 3)
INSERT INTO R VALUES(3, 4)
INSERT INTO R VALUES(3, 4)
INSERT INTO R VALUES(4, 1)
INSERT INTO R VALUES(4, 1)
INSERT INTO R VALUES(4, 1)
INSERT INTO R VALUES(4, 2)

SELECT a1.x, a2.y, COUNT(*)
FROM R a1, R a2
WHERE a1.y = a2.x
GROUP BY a1.x, a2.y;
